### ISSUE TITLE
Improve integration test performance

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM-live#12]
See comments on #10 - tests w/ simulator are too slow still, and can probably improved dramatically.

**Comment by sk1p** [comment]
The main problem should be fixed with https://github.com/LiberTEM/LiberTEM-live/commit/8056e38a05fb36dd71333c26b1bb78a132bfd989

**Comment by uellue** [comment]
Fix confirmed with data pipeline for #14, closing!
