### ISSUE TITLE
ConnectionReset Error when trying to read socket

### ISSUE THREAD

**Issue by adriente** [LiberTEM/LiberTEM-live#136]
Hello,

I am trying to use libertem_live to interface a MerlinEM. 
I am first trying to stream data using the following example : 
https://libertem.github.io/LiberTEM-live/merlin-lowlevel-example.html

The main modification I made is just changing the ip adress to connect to the PC that controls the MerlinEM hardware.

When executing : 
`data_source.socket.drain()` or `data_source.stream()`
I get the following error : 

> Traceback (most recent call last):
  File "C:\Users\supervisor\Git\medipix_server\NSLumiere\nionswift_plugin\IVG\QuantumPY\random_serv.py", line 118, in <module>
    client_handler(client_socket)
  File "C:\Users\supervisor\Git\medipix_server\NSLumiere\nionswift_plugin\IVG\QuantumPY\random_serv.py", line 75, in client_handler
    for frames in data_source.stream(num_frames = None, chunk_size = 16) :
  File "C:\ProgramData\Anaconda3\envs\nionswift-medipix-server\lib\site-packages\libertem_live\detectors\merlin\data.py", line 616, in stream
    yield from chunks
  File "C:\ProgramData\Anaconda3\envs\nionswift-medipix-server\lib\site-packages\libertem_live\detectors\merlin\data.py", line 570, in _read_and_decode
    acq_header = self.socket.read_acquisition_header()
  File "C:\ProgramData\Anaconda3\envs\nionswift-medipix-server\lib\site-packages\libertem_live\detectors\merlin\data.py", line 382, in read_acquisition_header
    length = self.read_mpx_length(cancel_timeout=cancel_timeout)
  File "C:\ProgramData\Anaconda3\envs\nionswift-medipix-server\lib\site-packages\libertem_live\detectors\merlin\data.py", line 368, in read_mpx_length
    hdr = self.read_unbuffered(15, cancel_timeout=cancel_timeout)
  File "C:\ProgramData\Anaconda3\envs\nionswift-medipix-server\lib\site-packages\libertem_live\detectors\merlin\data.py", line 330, in read_unbuffered
    bytes_read = self._socket.recv_into(
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

I am using libertem_live 0.2.1 and the MerlinEM readout software has the version : 1.4.0.180

Could you help me ?

**Comment by sk1p** [comment]
Hi, thanks for the report! For our setup, when we wanted to connect from the "outside" to the MerlinEM PC, we had to adjust the Windows Firewall settings to actually allow this. It should be possible to specifically allow connections on internal network adapters, for ports 6341 and 6342.

To diagnose if the firewall is the issue, I would suggest to (**temporarily!**) disable the firewall completely, and restart the script that calls `data_source.stream()`. If that works, it's clear that the firewall is the issue.

**Comment by adriente** [comment]
Hi,

Thanks for the very quick reply. 

I disabled the firewall and tried again but it also failed with the same error. In the lab we are already using the MerlinEM with another interface through the same network connection and it works. 

Is it worth trying myself to write a small python server and try to get the communication running ?

**Comment by sk1p** [comment]
Great that the firewall can be excluded as a culprit that way.

Can you also confirm that there is no other data connection at the same time? IIRC there is a limit of one "user" data connection, the MerlinEM software itself will have another connection. This should be visible in the TCP server status window of the MerlinEM software (I can check tomorrow how it's called exactly)

If you have your other interface running at the same time, you'll get an error like the one you are reporting.

**Comment by adriente** [comment]
I restarted both computer and I also checked using `netstat -a` that no additional connection was active and I got the same behaviour anyway.

The `with control, data_source :` statement passes correctly. 
The `control.cmd('STARTACQUISITION)` passes correctly too. 

When the data_source socket is try to recieve some data I get the 10054 win error.

**Comment by sk1p** [comment]
I'm a bit stumped - but it seems this specific error can also happen if the firewall on the PC running libertem-live blocks the **outgoing** connection. IIRC the Windows firewall shows a dialog the first time an application tries to create an outgoing connection, maybe that was denied at some point? Did you also try to deactivate the firewall temporarily on the PC running LiberTEM-live/nionswift? It's a bit weird that the control connection works, but the data connection doesn't...

In newer versions of the MerlinEM software there's also an error log - is anything logged there after trying to connect? Does the "TCP/IP Server (Data)" show a different status than Listening/Listen, or perhaps an error code that is not 0?

**Comment by adriente** [comment]
I am so sorry.... I made a mistake in the code and I was on the wrong port, it now works. I am closing this issue.

**Comment by sk1p** [comment]
No worries, great to hear you got it solved!
