### ISSUE TITLE
`BQLivePlot` not working on Windows

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM-live#3]
Not sure if this is an issue with how it is used here or with BQLivePlot. Should perhaps be filed in LiberTEM core?

## How to reproduce

Run the `run-udf-on-merlin-data.ipynb` example on Windows

## What happens

The computation runs, but there's no result display 

## What should happen

The live plot is visible in all its glory

## Workaround

Use `MPLLivePlot`

**Comment by uellue** [comment]
As a comment, also doesn't work for me on JupyterLab on Moellenstedt

**Comment by uellue** [comment]
Switching example to `MPLLivePlot` since the `BQLivePlot` seems to be fragile.

Example used for quick testing: https://github.com/glue-viz/bqplot-image-gl/blob/master/examples/basic.ipynb

**Comment by sk1p** [comment]
Maybe worth reporting upstream. The failure on JupyterLab @ moellenstedt is probably because of the old-ish jupyterlab version, but locally with up-to-date jupyter packages, it should work. Maybe we should have both examples, or pick `BQLivePlot` if `bqplot` is installed.

**Comment by uellue** [comment]
Could also come from my broken CUDA setup on Windows?

**Comment by sk1p** [comment]
It's using WebGL - you could check for errors on the devtools console

**Comment by uellue** [comment]
See https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-in-classic-jupyter-notebook for the fix!
