### ISSUE TITLE
`BQLivePlot`: uses different coordinate system

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM-live#4]
It has the origin at bottom-left by default. Might need to be flipped for consistency w/ mpl

**Comment by uellue** [comment]
LOL a recurring theme it seems... +1 for keeping it consistent between plots and using matplotlib default behavior as a reference, as described in https://libertem.github.io/LiberTEM/concepts.html#coordinate-system.

**Comment by uellue** [comment]
Fixed in https://github.com/LiberTEM/LiberTEM/pull/1011, closing!
